INSERT IGNORE INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(1, 'Uncategorized', 'uncategorized', 0),
(2, 'simple', 'simple', 0),
(3, 'grouped', 'grouped', 0),
(4, 'variable', 'variable', 0),
(5, 'external', 'external', 0),
(6, 'exclude-from-search', 'exclude-from-search', 0),
(7, 'exclude-from-catalog', 'exclude-from-catalog', 0),
(8, 'featured', 'featured', 0),
(9, 'outofstock', 'outofstock', 0),
(10, 'rated-1', 'rated-1', 0),
(11, 'rated-2', 'rated-2', 0),
(12, 'rated-3', 'rated-3', 0),
(13, 'rated-4', 'rated-4', 0),
(14, 'rated-5', 'rated-5', 0),
(15, 'Uncategorized', 'uncategorized', 0),
(31, 'art galleries', 'art-galleries', 0),
(32, 'communities', 'communities', 0),
(33, 'Ethnic enclave', 'ethnic-enclave', 0),
(34, 'forests Museums', 'forests-museums', 0),
(35, 'Gallery', 'post-format-gallery', 0),
(36, 'Mountains', 'mountains', 0),
(37, 'Cultural events', 'cultural-events', 0),
(38, 'National parks', 'national-parks', 0),
(39, 'Natural beauty beaches', 'natural-beauty-beaches', 0),
(40, 'Quote', 'post-format-quote', 0),
(41, 'Theme parks', 'theme-parks', 0),
(42, 'Top News', 'top-news', 0),
(43, 'Traditional tourist', 'traditional-tourist', 0),
(44, 'Mountains', 'mountains', 0),
(46, 'Link', 'post-format-link', 0),
(47, 'Beauty beaches', 'beauty-beaches', 0),
(48, 'Parks and Carnivals', 'parks-and-carnivals', 0),
(49, 'Video', 'post-format-video', 0),
(50, 'Museums', 'museums', 0),
(51, 'Audio', 'post-format-audio', 0),
(52, 'National parks', 'national-parks', 0),
(71, 'Hotel Menu', 'hotel-menu', 0),
(97, 'Tiptoe', 'tiptoe', 0),
(98, 'Tulips', 'tulips', 0),
(99, 'Washington', 'washington', 0),
(100, 'Carnivals', 'carnivals', 0),
(101, 'National', 'national', 0),
(102, 'Parks', 'parks', 0),
(103, 'beaches', 'beaches', 0),
(104, 'Beauty', 'beauty', 0),
(105, 'Cultural', 'cultural', 0),
(106, 'Museums', 'museums', 0),
(107, 'Image', 'post-format-image', 0),
(108, 'Footer New', 'footer-new', 0),
(109, 'Footer New 2', 'footer-new-2', 0),
(110, 'Non classifié(e)', 'non-classifiee', 0),
(111, 'Sin categorizar', 'sin-categorizar', 0),
(112, 'Air Conditioning', 'air-conditioning', 0),
(113, 'Elder Access', 'elder-access', 0),
(114, 'For Children', 'for-children', 0),
(115, 'Kitchen', 'kitchen', 0),
(116, 'No Smoking', 'smoking-allowed', 0),
(117, 'Parking', 'parking', 0),
(118, 'Pet Allowed', 'pet-allowed', 0),
(119, 'Pool', 'pool', 0),
(120, 'Wheelchair Access', 'wheelchair-access', 0),
(121, 'Wi-Fi Internet', 'wi-fi-internet', 0),
(122, 'Apartment', 'apartment', 0),
(123, 'House', 'house', 0),
(124, 'Condo', 'condo', 0),
(125, 'Townhome', 'townhome', 0),
(126, 'Studio', 'studio', 0),
(127, 'Duplex House', 'duplex-house', 0),
(128, 'Breakfast', 'breakfast', 0),
(129, 'page', 'page', 0);